
spring:
  datasource:
    password: letmein
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
    showSql: true
