# Generated by Django 2.1 on 2022-07-27 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 4, 25, 9, 707173, tzinfo=utc)),
        ),
    ]
